DATASET:
  TRAIN:
    TYPE: 'coco_wholebody'
    ROOT: '/ssd3/Benchmark/coco/'
    IMG_PREFIX: 'train2017'
    ANN: 'annotations/coco_wholebody_train_v1.0.json'
    AUG:
      FLIP: true
      ROT_FACTOR: 45
      SCALE_FACTOR: 0.35
      NUM_JOINTS_HALF_BODY: 8
      PROB_HALF_BODY: 0.3
  VAL:
    TYPE: 'coco_wholebody'
    ROOT: '/ssd3/Benchmark/coco/'
    IMG_PREFIX: 'val2017'
    ANN: 'annotations/coco_wholebody_val_v1.0.json'
  TEST:
    TYPE: 'coco_wholebody_det'
    ROOT: '/ssd3/Benchmark/coco/'
    IMG_PREFIX: 'val2017'
    DET_FILE: './exp/json/test_det_yolo.json'
    ANN: 'annotations/coco_wholebody_val_v1.0.json'
DATA_PRESET:
  TYPE: 'simple'
  LOSS_TYPE: 'L1JointRegression'
  SIGMA: 2
  NUM_JOINTS: 133
  IMAGE_SIZE:
  - 256
  - 192
  HEATMAP_SIZE:
  - 64
  - 48
MODEL:
  TYPE: 'FastPose_2Stage'
  PRETRAINED: '' #'./exp/2stage_aff-256x192_res50_lr1e-3_2x-2stage.yaml/model_179.pth'
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 50
  CONV_DIM: 128
  CROP_RESIZE:
  - 8
  - 6
  NUM_BODY_JOINTS: 23
  NUM_FACE_JOINTS: 68
  NUM_HAND_JOINTS: 42
LOSS:
  TYPE: 'L1JointRegression'
  NORM_TYPE: 'sigmoid'
  OUTPUT_3D: False
DETECTOR:
  NAME: 'yolo'
  CONFIG: 'detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05
TRAIN:
  WORLD_SIZE: 4
  BATCH_SIZE: 24
  BEGIN_EPOCH: 0
  END_EPOCH: 270
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 170
  - 200
  DPG_MILESTONE: 210
  DPG_STEP:
  - 230
  - 250
OTHERS: 
  TRAIN_BRANCH: True
  TEST_BRANCH: True
